### ISSUE TITLE
Mention rendering issue

### ISSUE THREAD

**Issue by rofe** [adobe/franklin-chat-ui#6]
When users get mentioned in Slack, they end up being rendere as links like this
```
slack://user?team=T06DUTYDF&id=W4SGCV4FB
```
which only works for Adobe folks. Until we are able to rewrite the links to go to a dedicated user side panel, we should probably just remove them and just keep the visual appearance of a link.

**Comment by vtsaplin** [comment]
The url is a deep link and formed by our code. This is clearly just a rendering bug.
